---
version: '2.1'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Asia/Shanghai}
      - UMASK_SET=022
      - WEBUI_PORT=${HTTP_PORT:-8081}
    volumes:
      - ./config:/config
      - ${DOWNLOAD_DIR:-./downloads}:/downloads
    ports:
      - ${HTTP_PORT:-8081}:${HTTP_PORT:-8081}
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped