---
version: '3.3'

services:
  zfile:
    image: zhaojun1998/zfile
    container_name: zfile
    restart: always
    ports:
      - '${HTTP_PORT:-8080}:8080'
    volumes:
      - './db:/root/.zfile-v4/db'
      - './logs:/root/.zfile-v4/logs'
      - '${UPLOAD_DIR:-./data}:/root/.zfile-v4/data'
      - './application.properties:/root/application.properties'
