---
version: '3'

services:
  lsky-pro:
    image: dko0/lsky-pro
    container_name: lsky-pro
    restart: always
    ports:
      - ${HTTP_PORT:-7791}:80
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lsky-pro}
      - MYSQL_USER=${MYSQL_USER:-lsky-pro}
      - MYSQL_PASSWORD=${MYSQL_PASS:-lsky-pro}
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql
    container_name: lsky-pro-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lsky-pro}
      - MYSQL_USER=${MYSQL_USER:-lsky-pro}
      - MYSQL_PASSWORD=${MYSQL_PASS:-lsky-pro}
    volumes:
      - ./mysql/db/:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d