---
version: '3'

services:
  app:
    image: joplin/server:latest
    container_name: joplin-server
    ports:
      - '${APP_PORT:-22300}:22300'
    restart: unless-stopped
    volumes:
      - ./data:/home/joplin
    env_file:
      - .env
