---
version: '3'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - ${HTTP_PORT:-3000}:3000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-umami}:${POSTGRES_PASS:-umami}@db:5432/${POSTGRES_DB:-umami}
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT:-replace-me-with-a-random-string}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-umami}
      POSTGRES_USER: ${POSTGRES_USER:-umami}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-umami}
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./umami-db-data:/var/lib/postgresql/data
    restart: always

