---
version: '3'

services:
  filebrowser:
    image: langren1353/filebrowser-ckplayer
    container_name: filebrowser
    restart: always
    ports:
      - '${HTTP_PORT:-8080}:80'
    volumes:
      - '${SRV_PATH:-./srv}:/srv'