---
version: '2.1'

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=${TZ:-Asia/Shanghai}
    volumes:
      - ./config:/config
      - ${MOVIE_DIR:-./movies}:/data/movies
      - ${TVSHOW_DIR:-./tvshows}:/data/tvshows
    ports:
      - ${HTTP_PORT:-8096}:8096
    restart: unless-stopped